# Generated by Django 5.2.1 on 2025-05-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fare',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
