# Generated by Django 5.2.1 on 2025-06-12 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('preferred_route', models.TextField(blank=True, null=True)),
                ('travel_time', models.TimeField(blank=True, null=True)),
                ('frequency', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_inputs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
