# Generated by Django 5.2.1 on 2025-06-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideinput',
            name='choice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rideinput',
            name='starting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rideinput',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
