# Generated by Django 5.2.1 on 2025-06-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_riderequest_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='seats',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
