# Generated by Django 5.2.1 on 2025-06-05 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_rides_seats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridefeedback',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ridefeedback',
            name='user',
        ),
        migrations.AddField(
            model_name='ridefeedback',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ridefeedback',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ridefeedback',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
