# Generated by Django 5.2.1 on 2025-06-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_remove_ridefeedback_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderequest',
            old_name='passenger',
            new_name='from_user',
        ),
        migrations.AlterUniqueTogether(
            name='riderequest',
            unique_together=set(),
        ),
    ]
