# Generated by Django 5.2.1 on 2025-06-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_rename_passenger_riderequest_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
