# Generated by Django 5.2.1 on 2025-06-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_alter_rides_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderequest',
            old_name='status',
            new_name='request_status',
        ),
    ]
