# Generated by Django 5.2.1 on 2026-05-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_ridechatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='route_path',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
